name: darzi_nearby
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.2.0
  firebase_core: ^3.14.0
  get_storage: ^2.1.1
  cached_network_image: ^3.2.3
  dio: ^5.3.2
  image: ^4.0.17
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.4.0
  gradient_borders: ^1.0.0
  get: ^4.6.6
  path_provider: ^2.1.2
  share_plus: ^11.0.0
  flutter_svg: ^2.0.9
  geolocator: ^14.0.1
  url_launcher: ^6.2.5
  url_strategy: ^0.3.0

  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/name.json
    - assets/logo/
    - assets/svg/
    - assets/png/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
