// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY5dAk22Ht8Plh2RGtASJriv8ow9uWiyA',
    appId: '1:352218423065:web:07f82e66fafa252bf76f88',
    messagingSenderId: '352218423065',
    projectId: 'darzinearby-e0457',
    authDomain: 'darzinearby-e0457.firebaseapp.com',
    storageBucket: 'darzinearby-e0457.appspot.com',
    measurementId: 'G-MGSZR3PKW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0TRqzK_tyc4Dm93tZO1a_FKQTRC7KUlU',
    appId: '1:492052639033:android:417fe96348ea33f3b00ce8',
    messagingSenderId: '492052639033',
    projectId: 'darzi-nearby',
    storageBucket: 'darzi-nearby.firebasestorage.app',
  );

}